-- INSERT INTO T_CUSTOMER (ID, NAME) VALUES (1, 'ACME');
--
-- INSERT INTO T_CUSTOMER_CREDENTIAL (ID, CUSTOMER_ID, USERNAME, PASSWORD) VALUES (1, '1', 'ACME',  '{bcrypt}$2a$10$Y3YcoPEqO6vsZsCijROmq.aAPv7HLRzbAvEjESBCkNMxCQKo8Hn8.');
--
-- INSERT INTO T_ASSET (ID, CUSTOMER_ID, ASSET_NAME, SIZE) VALUES (1, '1','TRY','1000');

INSERT INTO T_AUTH_PRINCIPAL ( REALM_OBJECT_ID, REALM, USERNAME, PASSWORD) VALUES ('admin', 'ADMIN', 'admin', 'admin')